// <auto-generated />
using System;
using BelbimEnv.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BelbimEnv.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250715230014_IlkMigrationIsmi")]
    partial class IlkMigrationIsmi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BelbimEnv.Models.PortDetay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BakirMAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FiberMAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIC_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SW_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SW_PORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("WWPN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("PortDetaylari");
                });

            modelBuilder.Entity("BelbimEnv.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cluster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostDns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IloIdracIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsttelkomEtiketId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kabin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KabinU")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RearFront")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcenterAdress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("BelbimEnv.Models.PortDetay", b =>
                {
                    b.HasOne("BelbimEnv.Models.Server", "Server")
                        .WithMany("PortDetaylari")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("BelbimEnv.Models.Server", b =>
                {
                    b.Navigation("PortDetaylari");
                });
#pragma warning restore 612, 618
        }
    }
}
